name: design_tokens_builder
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: '>=2.19.5 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  build: ^2.3.1
  build_config: ^1.1.1
  glob: ^2.1.1
  tuple: ^2.0.1
  math_expressions: ^2.4.0
  yaml: ^3.1.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter