name: greetings

on:
  - pull_request_target
  - issues

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: |
          Hi 👋🏽 Thank you for opening your first issue with simpleclub/design_tokens_builder ❤

          You can expect triage from us soon 🙂
          In the meantime, you can try to search for similar issues in our [issue database].

          [issue database]: https://github.com/simpleclub/design_tokens_builder/issues?q=is%3Aissue
